/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.paneles;

/**
 *
 * @author lexsw
 */
public class Panel_consultarPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form Panel_consultarPrestamos
     */
    public Panel_consultarPrestamos() {
        initComponents();
        this.setSize(816, 542);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel11.setFont(new java.awt.Font("Eras Medium ITC", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 170, 0));
        jLabel11.setText("Filtrar por:");
        add(jLabel11);
        jLabel11.setBounds(30, 20, 100, 23);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Estudiante", "Libro", "Categoria", "Fecha de prestamo" }));
        add(jComboBox1);
        jComboBox1.setBounds(150, 20, 160, 26);

        jTextField8.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jTextField8.setBorder(null);
        add(jTextField8);
        jTextField8.setBounds(330, 20, 340, 20);

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jSeparator8);
        jSeparator8.setBounds(330, 40, 340, 10);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "Título", "Autor", "Edición", "Notas", "Disponible"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 750, 340);

        jButton1.setText("Consultar");
        add(jButton1);
        jButton1.setBounds(340, 480, 110, 30);

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        jLabel1.setText("Campo: ");
        add(jLabel1);
        jLabel1.setBounds(330, 60, 340, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
