/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.paneles;

/**
 *
 * @author lexsw
 */
public class Panel_consultarLibro extends javax.swing.JPanel {

    /**
     * Creates new form Panel_consultarLibro
     */
    public Panel_consultarLibro() {
        initComponents();
        this.setSize(816, 542);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Campo_titulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        Campo_autor = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        Campo_categoria = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Boton_consultar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Campo_filtro = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Filtros = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        Campo_titulo.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        Campo_titulo.setBorder(null);
        add(Campo_titulo);
        Campo_titulo.setBounds(120, 70, 200, 20);

        jLabel7.setFont(new java.awt.Font("Eras Medium ITC", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 170, 0));
        jLabel7.setText("Título:");
        add(jLabel7);
        jLabel7.setBounds(30, 70, 54, 23);

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jSeparator4);
        jSeparator4.setBounds(120, 90, 200, 10);

        jLabel9.setFont(new java.awt.Font("Eras Medium ITC", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 170, 0));
        jLabel9.setText("Autor:");
        add(jLabel9);
        jLabel9.setBounds(390, 70, 56, 23);

        Campo_autor.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        Campo_autor.setBorder(null);
        add(Campo_autor);
        Campo_autor.setBounds(480, 70, 270, 20);

        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jSeparator6);
        jSeparator6.setBounds(480, 90, 270, 10);

        jLabel8.setFont(new java.awt.Font("Eras Medium ITC", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 170, 0));
        jLabel8.setText("Categoría: ");
        add(jLabel8);
        jLabel8.setBounds(30, 130, 98, 23);

        Campo_categoria.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        Campo_categoria.setBorder(null);
        add(Campo_categoria);
        Campo_categoria.setBounds(130, 130, 230, 20);

        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jSeparator7);
        jSeparator7.setBounds(130, 150, 230, 10);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "Título", "Categoría", "Autor", "Edición", "Notas", "Disponible"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 190, 750, 270);

        Boton_consultar.setText("Consultar");
        add(Boton_consultar);
        Boton_consultar.setBounds(340, 480, 110, 30);

        jLabel11.setFont(new java.awt.Font("Eras Medium ITC", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 170, 0));
        jLabel11.setText("Filtrar por:");
        add(jLabel11);
        jLabel11.setBounds(30, 20, 100, 23);

        Campo_filtro.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        Campo_filtro.setBorder(null);
        add(Campo_filtro);
        Campo_filtro.setBounds(270, 20, 370, 20);

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jSeparator8);
        jSeparator8.setBounds(270, 40, 370, 10);

        Filtros.setBackground(new java.awt.Color(255, 255, 255));
        Filtros.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        Filtros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Campos", "Notas", "Disponibles" }));
        add(Filtros);
        Filtros.setBounds(150, 20, 90, 26);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Boton_consultar;
    public javax.swing.JTextField Campo_autor;
    public javax.swing.JTextField Campo_categoria;
    public javax.swing.JTextField Campo_filtro;
    public javax.swing.JTextField Campo_titulo;
    public javax.swing.JComboBox<String> Filtros;
    public javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
